# Copyright (c) 2024 Ashraful Islam
site_name: Ashraful Islam
site_url: https://1-ashraful-islam.github.io
site_description: >-
  Ashraful Islam is a software engineer. He is a passionate learner. He loves to learn new
  technologies and share his knowledge with others.

# edit_uri: edit/main/docs/
# repo_url: https://github.com/1-ashraful-islam/1-ashraful-islam.github.io
copyright: >
  Copyright &copy; 2024 Ashraful Islam -
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/ai_logo_white_small.svg
  favicon: assets/images/favicon.ico
  icon:
    tag:
      default: fontawesome/solid/code
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
      python: fontawesome/brands/python
      html5-canvas: fontawesome/brands/html5
      tkinter: fontawesome/brands/python
      go: fontawesome/brands/golang
      java: fontawesome/brands/java
      cpp: simple/cplusplus
      nodejs: fontawesome/brands/node-js
      
  #   logo: logo
  features:
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - toc.integrate
    - toc.follow
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - social
  - privacy:
      assets: false
      # assets_exclude: 
      #   - cdn.jsdelivr.net/npm/mathjax@3/* 
      #   - giscus.app/*
  - tags:
      tags_file: tags.md
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true
  - blog:
      draft: false
      draft_on_serve: true
      draft_if_future_date: true
  - rss:
      enabled: !ENV [CI, false]
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true
      title: On this page
      permalink_title: Anchor link to this section for reference
      toc_depth: 3
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - abbr

# extras
extra_javascript:
  # make tables sortable
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  # for math equations
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css

extra:
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/1-ashraful-islam
        name: See my projects on GitHub
      - icon: fontawesome/brands/linkedin
        link: https://linkedin.com/in/1-ashraful-islam
        name: Connect with me on LinkedIn
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/a__islam
        name: Follow me on Twitter
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
    Python: python
    C++: cpp
    HTML5 Canvas: html5-canvas
    Python Tkinter: tkinter
    Go: go
    Java: java
    Node.js: nodejs

      
  # analytics:
  #     provider: google
  #     property: G-73LKLZCSB2
  #     feedback:
  #       title: Was this page helpful?
  #       ratings:
  #         - icon: material/emoticon-happy-outline
  #           name: This page was helpful
  #           data: 1
  #           note: >-
  #             Thanks for your feedback!
  #         - icon: material/emoticon-sad-outline
  #           name: This page could be improved
  #           data: 0
  #           note: >- 
  #             Thanks for your feedback! Help us improve this page by
  #             using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     The cookies are used to recognize your repeated visits and save your preferences, as well
  #     as to measure the effectiveness of the website content and whether users
  #     find what they're searching for. With your consent, you're helping to
  #     make the website serve your better.
  #   actions:
  #     - accept
  #     - reject
  #     - manage

# include folders outside docs that should trigger a reload
watch:
  - overrides
  - includes

# page tree
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - Projects:
    - projects/index.md
    - Pokédex: projects/pokedexCLI.md
    - Web Crawler: projects/web-crawler.md
    - Maze Generator and Solver: projects/maze-generator-and-solver.md
    - Weekend Projects:
      - Go Image to ASCII: projects/go-image2ascii.md
      - Pong Wars - Yin Yang Edition: projects/pong-war.md
  - Tags: tags.md
    

